# Generated by Django 5.2.1 on 2025-05-09 19:56

import core.utils
import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '600x600', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.utils.category_image_upload_path, verbose_name='Изображение'),
        ),
    ]
