# Generated by Django 5.2.1 on 2025-05-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcategory_cropping_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='numeric_value',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True, verbose_name='Числовое значение'),
        ),
        migrations.DeleteModel(
            name='AttributeValue',
        ),
    ]
