# Generated by Django 5.2.1 on 2025-05-11 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productattributevalue_numeric_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='numeric_value',
        ),
    ]
