# Generated by Django 5.2.1 on 2025-06-13 15:43

import django.db.models.deletion
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='blog_images')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('p', 'Paragraph'), ('h2', 'Heading 2'), ('h3', 'Heading 3')], max_length=2)),
                ('text', models.TextField()),
                ('bold', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.post')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
