# Generated by Django 5.2.1 on 2025-06-13 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название компании')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название точки')),
                ('is_official', models.BooleanField(default=True, verbose_name='Фирменный салон')),
                ('phones', models.TextField(help_text='Разделять переносом строки', verbose_name='Телефоны')),
                ('schedule', models.TextField(help_text='Разделять переносом строки', verbose_name='График работы')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('map_link', models.URLField(verbose_name='Ссылка на карту')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('map_link', models.URLField(verbose_name='Ссылка на карту')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.companycontact')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contacts.companycontact')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название телефона')),
                ('number', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='contacts.companycontact')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_icon', models.TextField(verbose_name='SVG иконка')),
                ('name', models.CharField(max_length=255, verbose_name='Название соцсети')),
                ('url', models.URLField(verbose_name='Ссылка на соцсеть')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='contacts.companycontact')),
            ],
        ),
    ]
