# Generated by Django 5.2.1 on 2025-05-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Для отображения контакта', verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='contact',
            name='link',
            field=models.CharField(default='Nulle', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Значение'),
        ),
    ]
