# Generated by Django 5.2.1 on 2025-05-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_contact_is_active_contact_link_alter_contact_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['name'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AddField(
            model_name='contact',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
