# Generated by Django 5.2.1 on 2025-05-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_alter_contact_options_contact_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
