# Generated by Django 5.2.1 on 2025-05-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_alter_contact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_active',
        ),
    ]
