# Generated by Django 5.2.1 on 2025-05-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_contact_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('privacy', 'Политика конфиденциальности'), ('cookies', 'Политика куки')], max_length=20, unique=True, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
