# Generated by Django 5.2.1 on 2025-05-19 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FooterLink',
        ),
    ]
